[package]
name = "mav2csv"
version = "0.0.1"
authors = ["Patrick José Pereira <patrickelectric@gmail.com>"]

[dependencies]
mavlink = { version = "0.6", default-features = false, features = [ "std", "serde" ] }
serde_json = "1"
stdweb = "0.4"
